version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - .:/var/www/html/Portfolio
      - ./etc/nginx/sites-available/portfolio.auca.ac.rw:/etc/nginx/conf.d/portfolio.conf
      - ./etc/ssl/certs/certificate.crt:/etc/ssl/certs/certificate.crt
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 26973_php
    volumes:
      - .:/var/www/html/Portfolio
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: 26973_portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwert@123
      MYSQL_DATABASE: portfolio
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local

networks:
  web:
    driver: bridge
